### ISSUE TITLE
why not libdxfrw as a git submodule?

### ISSUE THREAD

**Issue by omortie** [LibreCAD/LibreCAD_3#384]
Hi,
I'm trying to build the LibreCAD 3 but there is a pain in the build time finding libdxfrw (compiling and installing under MinGW) and also linking against it in LibreCAD cmake process.
I've finally managed to move the libdxfrw library to third_party directory of project root and it finally found it.
I wanted to ask if there is any reason why you would not use git submodule as you used for other dependencies like tinyspline for libdxfrw?
I can do it if you want.

**Comment by feragon** [comment]
Hi,
libdxfrw was separated in another repo because of its licensing. Adding a git submodule is not an issue, but distributing it would. 
However, it is distributed via conan: https://conan.io/center/libdxfrw

There is no guide on building LibreCAD using MinGW yet. Maybe you could help writing it here: https://github.com/LibreCAD/LibreCAD_3/wiki/Building
